image: node:22

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/
    - packages/*/node_modules/

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store
 - pnpm install

stages:
  - test
  - codegen
  - release

lint:
  stage: test
  script:
    - pnpm lint

test:
  stage: test
  script:
    - pnpm test:coverage
    - curl -Os https://cli.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov upload-process -t $CODECOV_TOKEN

build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - apps/*/dist
      - packages/*/dist

# Continuous Delivery
semantic-release:
  stage: release
  script:
    - pnpm build
    - pnpm exec multi-semantic-release
  variables:
    GIT_AUTHOR_NAME: 'gitlab-ci'
    GIT_AUTHOR_EMAIL: 'gitlab-ci@users.noreply.gitlab.com'
    GIT_COMMITTER_NAME: 'gitlab-ci'
    GIT_COMMITTER_EMAIL: 'gitlab-ci@users.noreply.gitlab.com'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

# Dependabot auto-merge functionality
# Note: GitLab has its own Dependency Scanning and Auto-merge features
# This can be configured in Settings > CI/CD > Merge request pipelines
# and Settings > General > Merge requests > Merge checks
regenerate-api:
  stage: codegen
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /Bump the oas group/
  script:
    - pnpm api:regen
    - pnpm format
    - |
      if [[ -n $(git status --porcelain) ]]; then
        git config user.name "gitlab-ci"
        git config user.email "gitlab-ci@users.noreply.gitlab.com"
        git add packages/rest/src/__generated__
        git commit -nm "feat(rest): Update OpenAPI Spec generated code"
        git push origin HEAD:$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      fi

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
