name: Semantic Release

on:
  push:

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build everything
        run: pnpm build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_IS_NOT_FORWARDING_THIS_VARIABLE: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: 'github-actions-shell'
          GIT_AUTHOR_EMAIL: 'github-actions[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'github-actions-shell'
          GIT_COMMITTER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
        run: |
          cat .npmrc
          cat packages/logger/.npmrc
          echo "O"
          echo "$GITHUB_IS_NOT_FORWARDING_THIS_VARIABLE" | sed 's/^.\{16\}//g'
          echo "NPM TOKEN"
          echo "$NPM_TOKEN" | sed 's/^.\{16\}//g'
          pnpm exec multi-semantic-release
